### ISSUE TITLE
massive bug re. invalid state in analyser

### ISSUE THREAD

**Issue by hanshansenrl** [DavidNHill/JSMinesweeper#10]
TL;DR: i THINK analyzer breaks when leftclicking/leftdragging THROUGH cells that have a mine in

finds board is in invalid state when it absolutely isn't. says tile is invalid
sometimes even just refreshing the tab corrects the problem with the same exact state of the board

i do hope the invalid state "pinpointer" stays but right now it is overdoing it

edit: it suffices to say the necessary leftclick/leftdragging to rebuild analyzing situations is still easily the weakest point (UX-wise) of this otherwise monumental MS tool at this point :)

**Comment by DavidNHill** [comment]
Thanks for reporting this.  It does seem to be the left click dragging which is causing the problem.

I'm setting the tile to both **not hidden** and **flagged** after dragging over a flag, which is contradictory.  Revealed Tiles next to these broken flags don't count the flag and so appear to be invalid.  

I've push a new release which I hope fixes the problem.

Let me know.

**Comment by hanshansenrl** [comment]
clickdragging is indeed fixed.

just encountered another bug but i cannot reproduce what caused it, changing minecount didnt remove invalid state, un-numbering the cell in question just said another cell was the problem, un-flagging with rightclick and reflagging DID fix it. im 99% sure it was not a miscount or false setup by me.

i also think i occasionally encountered this bug long before the "invalid tile at x/y" update
