### ISSUE TITLE
showSaveFilePicker not supported in Firefox

### ISSUE THREAD

**Issue by Lem** [DavidNHill/JSMinesweeper#11]
I tried to download a board in the analyzer, but nothing poped up.

Taking a look into the console reviled:
```
Save file picker exception: window.showSaveFilePicker is not a function
```

As I'm using Firefox 120.0 it seems that my browser does not support a download. Take a look at the "Browser compatibility"-section of https://developer.mozilla.org/en-US/docs/Web/API/Window/showSaveFilePicker

**Comment by DavidNHill** [comment]
Thanks for reporting this.  

I'll see if I can revert to doing a file download if ShowSaveFilePicker is not available.

**Comment by DavidNHill** [comment]
The links should download the position or mbf data now when the file picker isn't available.

Let me know if this works for you, or not.

**Comment by Lem** [comment]
> Let me know if this works for you, or not.

It is now working. Thanks
