### ISSUE TITLE
The site is unplayable on mobile

### ISSUE THREAD

**Issue by BogdanDidukh2003** [DavidNHill/JSMinesweeper#14]
There is no possibility for player to place a flag from touch screen
The layout is broken too, but there is a workaround by opening a desktop version.
![Screenshot_20240624-212611](https://github.com/DavidNHill/JSMinesweeper/assets/74701445/0424077a-7627-4a39-867b-350376c35970)
The horizontal layout from a phone is broken a bit too
![Screenshot_20240624-213718](https://github.com/DavidNHill/JSMinesweeper/assets/74701445/9100499c-974b-45c2-b8eb-ed1e07fcddc4)

**Comment by deand0n** [comment]
I can take a look at layout issue, if you don't mind @DavidNHill

**Comment by DavidNHill** [comment]
I don't have the time or the knowledge to make the site work well for mobile devices.

If you want to suggest simple changes, or submit pull requests then I'll consider them.
