### ISSUE TITLE
board hover tooltip in the way

### ISSUE THREAD

**Issue by hanshansenrl** [DavidNHill/JSMinesweeper#16]
i couldve sworn its position never bothered me before.

especially if its multiline (progress etc) in the analyser its always in the way now. send it 20 pixels to the right pls

**Comment by DavidNHill** [comment]
I made a few changes to try and be more touch device friendly.  The tooltip got accidently shifted a bit to the left as part of that.  

I've moved it more to the right as you suggest,

**Comment by hanshansenrl** [comment]
> got accidently shifted a bit to the left

did it really?? did u shift it back to the right as much as it was before the touchdevice update or even more? anyway i see which line of code u changed so i can tune it myself if i wanted to
