### ISSUE TITLE
Efficiency mode broken?

### ISSUE THREAD

**Issue by tchesket** [DavidNHill/JSMinesweeper#4]
Maybe I'm doing something wrong, but playing efficiency mode with hints on, I can't figure out how to use chording. Also, after placing a mine the game seems to freeze up and not let me click anything. Please help, thank you

**Comment by tchesket** [comment]
It seems to freeze completely whenever I try to chord, not sure what's going on

**Comment by DavidNHill** [comment]
Chording is done by left clicking the tile to chord.

Does it work okay when not in efficiency mode?

What size board are you using, efficiency can be very cpu intensive?

What browser are you using?

When the player stops responding can you go to the console ( right click somewhere off the board / select inspect / select console tab) and see if there are any errors or messages indicating a problem.

**Comment by DavidNHill** [comment]
I've fixed the error when the middle mouse button is pressed.
